import { ids, info, streams, type Task, type TaskId } from '../model'
import { criticalEdge, type Schedule } from '../schedule'
import { displayDate } from '../calendar'
const positions: Record<TaskId,[number,number]>={P1:[18,20],P2:[262,20],T1:[18,140],T2:[262,140],A1:[18,260],A2:[506,260],E1:[18,380],E2:[750,380]}
export function DependencyMap({tasks,calculated,selected,onSelect,view,onView}:{tasks:Task[];calculated:Schedule;selected:TaskId;onSelect:(id:TaskId)=>void;view:'map'|'list';onView:(view:'map'|'list')=>void}) {
 return <section id="dependencies" className="surface map-panel" aria-labelledby="dependencies-title">
  <div className="section-top"><div><p className="eyebrow">01 / Trace the handoffs</p><h2 id="dependencies-title">One program. Four workstreams.</h2></div><div className="segmented" aria-label="Dependency view"><button type="button" aria-pressed={view==='map'} onClick={()=>onView('map')}>Map</button><button type="button" aria-pressed={view==='list'} onClick={()=>onView('list')}>List</button></div></div>
  <div className="legend"><span><i className="critical-dot"/> Critical, zero slack</span><span><i className="neutral-dot"/> Has schedule slack</span><span>Arrow = prerequisite handoff</span></div>
  {view==='map' ? <div className="map-scroll" role="region" tabIndex={0} aria-label="Scrollable dependency map; equivalent list available above"><div className="map-canvas">
   <svg className="connectors" viewBox="0 0 970 490" aria-hidden="true"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="#6b8294"/></marker></defs>{tasks.flatMap(task=>task.predecessors.map(pred=>{const [x1,y1]=positions[pred],[x2,y2]=positions[task.id];const sourceX=x1+196,targetX=x2;const critical=criticalEdge(calculated,pred,task.id);return <path key={`${pred}-${task.id}`} d={`M${sourceX} ${y1+46} C${sourceX+35} ${y1+46},${targetX-35} ${y2+46},${targetX} ${y2+46}`} className={critical?'edge critical-edge':'edge'} markerEnd="url(#arrow)"/>}))}</svg>
   {ids.map(id=>{const task=calculated.tasks[id];return <button key={id} type="button" className={`map-node node-${id} ${task.critical?'is-critical':''} ${selected===id?'selected':''}`} aria-label={`${id} ${info[id].name}, ${info[id].owner}, finish ${displayDate(task.finishDate)}, ${task.slack} days slack. Inspect deliverable`} aria-pressed={selected===id} onClick={()=>onSelect(id)}><span className="node-top"><span>{id} / {info[id].stream}</span><span aria-label={task.critical?'Critical':'Slack'}>{task.critical?'◆':'○'}</span></span><strong>{info[id].name}</strong><span className="node-bottom">{displayDate(task.finishDate)} <span>{task.slack===0?'Critical':`${task.slack}d slack`}</span></span></button>})}
  </div></div> : <div className="dependency-list">{streams.map(stream=><section key={stream} aria-label={stream}><h3>{stream}</h3>{tasks.filter(t=>info[t.id].stream===stream).map(task=><article key={task.id} className={`list-node ${selected===task.id?'selected':''}`}><button type="button" onClick={()=>onSelect(task.id)} aria-pressed={selected===task.id}>{task.id} · {info[task.id].name}</button><p>{info[task.id].owner} · {displayDate(calculated.tasks[task.id].startDate)}–{displayDate(calculated.tasks[task.id].finishDate)} · {calculated.tasks[task.id].slack} working days slack</p><p><strong>Predecessors:</strong> {task.predecessors.join(', ')||'None — starts at sample origin'}</p><p><strong>Handoff:</strong> {task.handoffMode==='rehearsal'?'Reviewed rehearsal pack; reconcile real contract later':info[task.id].handoff}</p><p><strong>Outcome:</strong> {info[task.id].outcome}</p></article>)}</section>)}</div>}
  <p className="map-note">Select a deliverable to inspect its owner, outcome and handoff. If the map extends beyond the panel, scroll sideways or choose List. Dates use the declared weekday calendar.</p>
 </section>
}
