import { useState } from 'react'
import { info, type Task, type TaskId } from '../model'
import type { Schedule } from '../schedule'
import { displayDate } from '../calendar'
export function Inspector({task,calculated,onPreview}:{task:Task;calculated:Schedule;onPreview:(id:TaskId,predecessors:string,duration:number)=>void}) {
 const [predecessors,setPredecessors]=useState(task.predecessors.join(', ')),[duration,setDuration]=useState(String(task.duration))
 const details=info[task.id],slot=calculated.tasks[task.id]
 return <aside className="surface inspector" aria-labelledby="inspector-title"><p className="eyebrow">Deliverable / {task.id}</p><h2 id="inspector-title">{details.name}</h2><div className="owner"><span className="avatar">{details.owner.split(' ').map(s=>s[0]).join('')}</span><div><strong>{details.owner}</strong><small>Accountable owner · {details.stream}</small></div></div><dl className="facts"><div><dt>Handoff condition</dt><dd>{task.handoffMode==='rehearsal'?'Reviewed rehearsal pack; reconcile the real contract before evidence.':details.handoff}</dd></div><div><dt>Intended outcome</dt><dd>{details.outcome}</dd></div><div><dt>Current commitment</dt><dd>{displayDate(slot.startDate)}–{displayDate(slot.finishDate)} · {slot.slack} working days slack</dd></div></dl><form onSubmit={event=>{event.preventDefault();onPreview(task.id,predecessors,Number(duration))}}><h3>Explore a handoff change</h3><label htmlFor="duration">Duration / working days</label><input id="duration" type="number" min="1" max="20" step="1" required value={duration} onChange={e=>setDuration(e.target.value)}/><label htmlFor="predecessors">Predecessor IDs</label><input id="predecessors" value={predecessors} onChange={e=>setPredecessors(e.target.value)} aria-describedby="handoff-help" placeholder="None"/><p id="handoff-help" className="field-help">Comma-separated IDs. Permitted: {details.allowed.join(', ')||'none'}. Required: {details.required.filter(id=>!(task.handoffMode==='rehearsal'&&id==='P1')).join(', ')||'none'}. Circular and missing handoffs are rejected.</p><button type="submit" className="button secondary">Preview handoff change <span aria-hidden="true">↗</span></button></form></aside>
}
