import { useEffect, useRef } from 'react'
import type { Plan } from '../model'
import { fingerprint, taskPatch, type Proposal } from '../proposals'
import { schedule } from '../schedule'
import { displayDate } from '../calendar'
export function ProposalDialog({proposal,plan,onCancel,onConfirm}:{proposal:Proposal;plan:Plan;onCancel:()=>void;onConfirm:()=>void}) {
 const ref=useRef<HTMLDialogElement>(null),stale=proposal.expected!==fingerprint(plan),before=schedule(plan.tasks),after=schedule(proposal.candidate.tasks)
 useEffect(()=>{const dialog=ref.current,previous=document.activeElement as HTMLElement|null;dialog?.showModal();return ()=>{dialog?.close();if(previous?.isConnected) previous.focus()}},[])
 const patches=taskPatch(plan.tasks,proposal.candidate.tasks),decision=proposal.kind==='decision'?proposal.candidate.decisions.at(-1):undefined
 return <dialog ref={ref} className="proposal-dialog" aria-labelledby="proposal-title" onCancel={event=>{event.preventDefault();onCancel()}}><p className="eyebrow">Review before confirming</p><h2 id="proposal-title">{proposal.title}</h2><p>{proposal.description}</p>{stale?<p role="alert" className="alert">This preview is stale because the current plan changed. Cancel and preview again.</p>:null}<div className="preview-dates"><div><span>Current readiness</span><strong>{displayDate(before.finishDate)}</strong></div><span aria-hidden="true">→</span><div><span>Proposed readiness</span><strong>{displayDate(after.finishDate)}</strong></div></div><h3>What changes</h3>{patches.length?<ul>{patches.map(p=><li key={p}>{p}</li>)}</ul>:<p>{proposal.kind==='decision'?'One decision record is added; all deliverables remain as currently confirmed.':'Schedule definitions already match the original sample; local decisions and risk records are cleared.'}</p>}<p><strong>Affected commitments:</strong> {proposal.changed.length?proposal.changed.join(', '):'No deliverable dates or handoffs change.'}</p><p><strong>Cost:</strong> {proposal.cost}</p><p><strong>Residual risk:</strong> {proposal.residual}</p>{decision?<dl className="decision-review"><div><dt>Decision owner</dt><dd>{decision.owner}</dd></div><div><dt>Decision needed</dt><dd>{decision.needed}</dd></div><div><dt>Evidence</dt><dd>{decision.evidence}</dd></div><div><dt>Due point</dt><dd>{decision.due}</dd></div></dl>:null}<p className="field-help">Confirmation changes only this local fictional scenario. {proposal.kind==='reset'?'Reset can be undone once in this tab.':'Undo restores the last confirmed snapshot in this tab until refresh or an external update.'}</p><div className="dialog-actions"><button type="button" className="button secondary" onClick={onCancel}>Cancel preview</button><button type="button" className="button primary" disabled={stale} onClick={onConfirm}>{proposal.kind==='decision'?'Confirm decision record':proposal.kind==='reset'?'Confirm reset':'Confirm proposal'}</button></div></dialog>
}
