import {it,expect} from 'vitest'
import {freshPlan} from './model'
import {confirm,delayProposal,decisionProposal} from './proposals'
import {loadStorage,saveStorage,parsePlan,StorageConflict} from './storage'
const mock=(raw:string|null=null)=>{let data=raw;return ()=>({getItem:()=>data,setItem:(_key:string,value:string)=>{data=value}})}
it('round trips confirmed decisions, risks and schedule snapshots',()=>{const p=confirm(freshPlan(),delayProposal(freshPlan())),c=confirm(p,decisionProposal(p,{owner:'Mira Vale',needed:'Choose scope reduction',evidence:'Pack delay to October 13',due:'2026-10-09'})),get=mock();saveStorage(c,null,'saved',false,get);expect(loadStorage(get).plan).toEqual(c)})
it('preserves invalid data until explicit reset',()=>{const get=mock('{broken');expect(loadStorage(get).mode).toBe('invalid');expect(()=>saveStorage(freshPlan(),'{broken','invalid',false,get)).toThrow(/invalid/);expect(get().getItem()).toBe('{broken');saveStorage(freshPlan(),'{broken','invalid',true,get);expect(loadStorage(get).mode).toBe('saved')})
it('catches throwing storage getter and quota failure',()=>{const get=()=>{throw new Error('blocked')};expect(loadStorage(get).mode).toBe('memory');expect(saveStorage(freshPlan(),null,'saved',false,get).mode).toBe('memory');expect(saveStorage(freshPlan(),null,'saved',false,()=>({getItem:()=>null,setItem:()=>{throw new Error('quota')}})).mode).toBe('memory')})
it('rejects same-revision cross-tab content changes before mutation',()=>{const p=freshPlan(),get=mock(JSON.stringify(p));const token=loadStorage(get).token;const altered=freshPlan();altered.tasks[2].duration=5;get().setItem('',JSON.stringify(altered));expect(()=>saveStorage(p,token,'saved',false,get)).toThrow(StorageConflict);expect(loadStorage(get).plan.tasks[2].duration).toBe(5)})
it('rejects malformed duration, snapshots, unknown IDs, incompatible schema, and cycles',()=>{const p=freshPlan();expect(parsePlan('{"schema":2}')).toBeNull();p.tasks[0].duration=Infinity;expect(parsePlan(JSON.stringify(p))).toBeNull();p.tasks[0].duration=3;p.tasks[0].predecessors=['P2'];expect(parsePlan(JSON.stringify(p))).toBeNull();const c=confirm(freshPlan(),decisionProposal(freshPlan(),{owner:'Mira Vale',needed:'review option',evidence:'sample evidence',due:'2026-10-09'}));c.decisions[0].commitments.finishDate='2026-10-30';expect(parsePlan(JSON.stringify(c))).toBeNull()})
it('rejects contradictory aggregate snapshots and duplicate critical members',()=>{const c=confirm(freshPlan(),decisionProposal(freshPlan(),{owner:'Mira Vale',needed:'review option',evidence:'sample evidence',due:'2026-10-09'}));c.decisions[0].commitments.length=15;c.decisions[0].commitments.finishDate='2026-10-23';expect(parsePlan(JSON.stringify(c))).toBeNull();c.decisions[0].commitments.length=12;c.decisions[0].commitments.finishDate='2026-10-20';c.decisions[0].commitments.critical.push('T1');expect(parsePlan(JSON.stringify(c))).toBeNull()})
